# Generated by Django 5.2.6 on 2025-09-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('movie', '🎬 Фильм'), ('series', '📺 Сериал'), ('book', '📚 Книга'), ('song', '🎵 Песня'), ('game', '🎮 Игра'), ('poem', '📝 Стихотворения'), ('speech', '🎤 Выступление'), ('social', '📱 Соцсети'), ('proverb', '💬 Пословица'), ('other', '❓ Другое')], max_length=10),
        ),
    ]
